[tool.poetry]
name = "music-download"
version = "0.1.0"
description = ""
authors = ["Miguel Condesso <mcondesso@mail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
mutagen = "1.48.1"
pytubefix = { git = "https://github.com/felipeucelli/pytubefix.git", branch = "botGuard" }
youtube-search = "2.2.0"
tqdm = "4.70.0"
moviepy = "^2.2.1"


[tool.poetry.group.dev.dependencies]
black = "26.5.1"
ipdb = "0.13.13"
isort = "8.0.1"
mypy = "2.3.0"
pylint = "4.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
